modLoader="javafml"
loaderVersion="[45,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Underwater%20Enchanting"
logoFile="icon.png"

[[mods]]
modId="underwaterenchanting"
version="2.3"
displayName="Underwater Enchanting"
displayURL="https://curseforge.com/minecraft/mc-mods/underwater-enchanting"
authors="Rick South"
description='''Allows the use of the enchantment table under water with maximum levels via bookshelves.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Adam E, Alister, aternosorg, Cherriesaurus, FireStriker, Greg Johnson, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Shana Gitnick, silver Bowsman, Tyler Behl   

If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.underwaterenchanting]]
    modId="collective"
    mandatory=true
    versionRange="[6.65,)"
    ordering="NONE"
    side="BOTH"